### ISSUE TITLE
Rev6 errata tracking

### ISSUE THREAD

**Issue by Qix-** [oro-os/link#53]
- [x] pins 4 and 5 of power connector (J2) must be shorted
- [ ] pin 2 of power connector (J2) must go to to SUT's PSU_ON pin (green line); PS_OK is no longer used and MCU pin must be configured as pullup input
- [x] ethernet controller chip enable MOSFETs (IC6 / IC9) omitted;  pins 2 and 3 must be shorted
- [x] indicator lights enable MOSFET (IC16) omitted; pins 2 and 3 must be shorted
- [x] OLED charge pump enable pull-up resistor (R24) omitted
- [x] OLED VCC MOSFET (IC5) omitted; pins 2 and 3 must be shorted, and pin 1 needs lead wire to pin 1 of OLED charge pump (IC4)
- [x] OLED enable MOSFET (IC3) omitted; pins 2 and 3 must be shorted
- [x] SUT power and reset MOSFETs (Q2 / Q3) must be held high for >=100ms to trigger
- [x] indicator lights current limiting resistor (R58) _should_ be replaced with 10k resistor
  - future fix should use 12-13k
- [x] USB VBUS line (PA9) needs to have a port for it to connect to the VBUS line on the MB. Might also need a common ground (even though... probably not, but can't hurt).

**Comment by Qix-** [comment]
> pin 2 of power connector (J2) must go to to SUT's PSU_ON pin (green line); PS_OK is no longer used and MCU pin must be configured as pullup input

I'm not entirely sure this makes sense to me. I don't know what I was trying to convey here. Going to ignore it for now because I can't see any corresponding changes on the board itself.
